services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: app
    ports: ["5432:5432"]
  backend:
    build:
      context: .
      dockerfile: infrastructure/docker/backend.Dockerfile
    ports: ["8000:8000"]
    depends_on:
      - db
